config/routes.rb
Rails.application.routes.draw do
  get 'movies/new'

  get 'slots/new'
  
  get 'movies/search'
  get 'channels/search'
  post 'channels/search'
  post 'channels/create_reminders'

  get 'channels_index' => "channels#index", :as =>"home"
 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "channels#index"
  resources :users
  resources :sessions
  resources :channels
  resources :slots
  resources :movies
  
  

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :slots
  has_many :movies, :through => :slots
  def self.currently_playing()
    current_time=Time.now.strftime("%I")
    current_time= current_time.to_i
    timeslot=current_time/3
    channel = Slot.joins(:channel,:movie).select("slots.id as slot_id,slots.timeslot as timeslot,channels.name as ch_name,channels.id as ch_id,channels.description as ch_desc,channels.chImage as ch_image,movies.id as mv_id,movies.description as mv_desc,movies.name as mv_name,movies.length as mv_length,movies.mvImage as mv_image").where("timeslot =?",timeslot)

    if channel
      return channel
    else
      1
    end
  end
   def self.give_content(id,timeslot)
     content = Slot.joins(:channel,:movie).select("slots.id as slot_id,slots.timeslot as timeslot,channels.name as ch_name,channels.id as ch_id,channels.description as ch_desc,channels.chImage as ch_image,movies.id as mv_id,movies.description as mv_desc,movies.name as mv_name,movies.length as mv_length,movies.mvImage as mv_image").where("channel_id =? and timeslot >?",id,timeslot)
   if content
      return content
    else
      1
    end
  end

  def self.give_reminder_for_user(user_id)
    reminder=Reminder.where("user_id=?",user_id)
    if reminder
      return reminder
    else
      1
    end
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :slots
  has_many :channels, :through => :slots

  def self.search(search)
    result= Slot.joins(:channel,:movie).select("slots.timeslot as timeslot,channels.name as ch_name,channels.id as ch_id,channels.description as ch_desc,channels.chImage as ch_image,movies.id as mv_id,movies.description as mv_desc,movies.name as mv_name,movies.length as mv_length,movies.mvImage as mv_image").where("movies.name =?",search)

    if result
      return result
    else
      1
    end
  end
  def self.get_movie(id)
    result= Slot.joins(:channel,:movie).select("slots.timeslot as timeslot,channels.name as ch_name,channels.id as ch_id,channels.description as ch_desc,channels.chImage as ch_image,movies.id as mv_id,movies.description as mv_desc,movies.name as mv_name,movies.length as mv_length,movies.mvImage as mv_image").where("movies.id=?",id)

    if result
      return result
    else
      1
    end
  end
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
   belongs_to :user
   belongs_to :slot
   
end
  

app/models/slot.rb
class Slot < ActiveRecord::Base
  belongs_to :channel
  belongs_to :movie
  has_many :reminders
  has_many :users, :through => :reminders
end

app/models/user.rb
class User < ActiveRecord::Base 
  attr_accessor :password
  before_save :encrypt_password
  has_many :reminders
  has_many :slots, :through => :reminders
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.get_channel_movie_data
    maildata = Slot.joins(:channel,:movie).select("slots.id as slot_id,slots.timeslot as timeslot,channels.name as ch_name,movies.name as mv_name")
  if maildata
      return maildata
    else
      1
    end
  end

  def self.get_user_slot_data
    userdata = Reminder.joins(:user,:slot).select("slots.id as slot_id,users.email as user_email")
  if userdata
      return userdata
    else
      1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
   @list=Channel.currently_playing
  end
  def show
    @channel = Channel.find(params[:id])
    @data=params[:data]
    
    @content=Channel.give_content(params[:id],@data["timeslot"])
    @reminderDetails=Channel.give_reminder_for_user(@data["user_id"])
  end
  def search
    redirect_to movies_search_path(:search => params[:search])
    #redirect_to controller: 'movies', action: 'edit', id: params[:search]
  end
  def create_reminders
    
    @reminder=Reminder.new
    @reminder.user_id=params[:user_id]
    @reminder.slot_id=params[:slot_id]
    @reminder.save
    flash[:notice] = "Reminder set Successfully"
    redirect_to :back
    
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
  end
  def show
   @movie=Movie.get_movie(params[:id])
  end
  def search
    @movie=Movie.search(params[:search])
  end
  
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  def new
    
    @slot=Slot.new
    @movie=Movie.all
    @channel=Channel.all
  end
  def create
   
   @slot=Slot.new(slot_params)
   if @slot.save
     flash[:notice] = "Congratulations you have registered successfully"
     redirect_to root_url
   else
      flash[:notice] = "Something Went wrong! try again"
      redirect_to root_url
   end
  end
  private
    def slot_params
      params.require(:slot).permit(:channel_id, :movie_id, :timeslot)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user=User.new
  end
  def create
   @user=User.new(user_params)
   if @user.save
     flash[:notice] = "Congratulations you have registered successfully"
     redirect_to root_url
   else
      flash[:notice] = "Something Went wrong! try again"
      redirect_to root_url
   end
  end
  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/index.html.erb
<div class="jumbotron text-center">
<h1> Movies </h1>
<p> Search for your favourite movie timings
</p>

<%= form_tag :action => 'search', :class=>'form-inline'  do %>
  <%= text_field_tag :search, params[:search], size:50,placeholder:"Eg. Batman or Dilwale",class:"form-control search-bar" %>
  <div class="row">
     <div class="span6 offset1">
         <%= submit_tag "Search", :class => "btn-primary btn btn-metric-current" ,:name => nil %>
      </div>
   </div>
<% end %>
</div>
<div class="row currently-showing" >Now Showing</div>
<div id="movies" class="container-fluid text-center">
  <div class="row">
	  <% @list.each do |row| %>
	      <div class="col-sm-4">
		 <div class="thumbnail">
		    <a href="#">
		        <%= image_tag(row.mv_image,:alt =>row.mv_name,:class => "img-responsive") %>
                    
		    </a>
		  <p>
                  <%= image_tag(row.ch_image,:class => "img-responsive index-channel-image") %>
<span style="display: inline-block;"> <strong><%= link_to row.ch_name, channel_path(:data=> {:slot_id=>row.slot_id,:timeslot =>row.timeslot,:ch_id=>row.ch_id,:ch_desc=>row.ch_desc,:ch_name=>row.ch_name,:ch_image=>row.ch_image,:user_id => session[:user_id],:mv_id=>row.mv_id ,:mv_image=>row.mv_image,:mv_name=>row.mv_name,:mv_desc=>row.mv_desc ,:mv_length=>row.mv_length},:id => row.ch_id) %>
              </strong> </span></p>
		 </div>
	       </div>
	   <% end %>
   </div>
	
</div>
</div>

app/views/channels/show.html.erb
<div class="alert alert-success wrapper">
<%= image_tag(@data["ch_image"],:alt =>@data["ch_name"],:class => "img-responsive") %>
<h1> <b>Welcome to <%= @data["ch_name"] %></b></h1>
<h4> <%= @data["ch_desc"] %></h4>
</div>
<div class="row ">
  <div class="row inner" >Currently Showing</div>
  <div class="col-md-5 size-image">
     <%= image_tag(@data["mv_image"],:alt =>@data["mv_name"],:class => "img-responsive") %>
     
  </div>
  <div class="col-md-7">
   <div class="panel panel-primary newpanel">
     <h2><div class="panel-heading"><strong><%=link_to @data["mv_name"] ,movie_path(:id => @data["mv_id"]) %></strong></div></h2>
      <div class="desc"><strong>Movie Description</strong></div>
      <div class="panel-body">
	  <h5><strong>Title: <%= @data["mv_name"] %></strong></h5>
	  <h5><strong>Description: <%= @data["mv_desc"] %></strong></h5>
	  <h5><strong>Length: <%= @data["mv_length"] %></strong></h5>
          <h5><strong>Show Time: <%= @data["timeslot"].to_i*3 %>:00 hrs - <%= @data["timeslot"].to_i*3+2 %>:00 hrs </strong></h5>

          <% if @reminderDetails.index{|r| r.slot_id.to_s == @data["slot_id"].to_s} %>
             <div class="reminded"> Reminded</div>
          <% elsif current_user %>
              <%= button_to 'Remind Me', {:controller => "channels", :action => "create_reminders",:user_id=> session[:user_id],:slot_id=>@data["slot_id"]} , :method=>:post,:class =>"btn btn-success"   %>
	  <% else %>
            
	    <div class="btn-primary reminder-signup"><%= link_to "SIGN UP TO SET REMINDER", sign_up_path %></div>
	  <% end %>
           
	  </div>
    </div>
</div>
</div>
<br>
<div class="row inner" >Coming Up Next</div>
<br>

<% @content.each do |row| %>
  <div class="row">  
	        <div class="col-md-4 upcoming">
                       <%= image_tag(row.mv_image,:alt =>row.mv_name,:class => "img-responsive") %>
 		       
                 </div>
		  <div class="col-md-4">
			 <h5>Movie Name :  <%=link_to row.mv_name,movie_path(:id => row.mv_id) %></h5>
			 <h5>Description : <%= row.mv_desc %></h5>
			 <h5>Length : <%= row.mv_length %> </h5>
			 <h5>Show Time : <%= row.timeslot.to_i*3 %>:00 hrs - <%= (row.timeslot.*3)+2 %>:00 hrs</h5>
	          </div>
		  <div class="col-md-4">
		         <% if @reminderDetails.index{|r| r.slot_id.to_s == row.slot_id.to_s} %>
			     <div class="reminded"> Reminded</div>
			  <% elsif current_user %>
			      <%= button_to 'Remind Me', {:controller => "channels", :action => "create_reminders" ,:user_id=> session[:user_id],:slot_id=>row.slot_id} , :method=>:post ,:class =>"btn btn-success" %>
			  <% else %>
                               <div class="btn-primary reminder-signup"><%= link_to "SIGN UP TO SET REMINDER", sign_up_path %></div>
			  <% end %>
                   </div>
	       
	   
   </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag 'bootstrap.min.css','common', :media => 'screen' %>
  
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js', 'bootstrap.min.js','data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "LOGO", root_url, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">	   
      <ul class="nav navbar-nav navbar-right">
        <li ><a href="#about">ABOUT</a></li>
        <li><a href="#contact">CONTACT</a></li>
        <li>
	  <% if current_user %>
            <li><a href="#"  data-toggle="popover" title="Notification" > <span class="glyphicon glyphicon-user logo"> </span> </a></li>
	    <li><a><%= current_user.email %></a></li>
	    <li><%= link_to "LOG OUT", log_out_path %></li>
        </li>
        <li>
	  <% else %>
	    <%= link_to "SIGN UP", sign_up_path %>
         </li>
         <li>
	    <%= link_to "LOG IN", log_in_path %>
	  <% end %>
	 </li>
      </ul>
    </div>
  </div>
</nav>


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

app/views/movies/search.html.erb
<% if !@movie[0].nil? %>
   <div id="heroArea" class="clearfix search-wrapper">
            
		<div class="container">
                   <h1> <%= @movie[0].mv_name%> </h1>
                   <%= image_tag(@movie[0].mv_image,:class => "img-responsive movie-image") %>
		    


			<h3>Duration : <%= @movie[0].mv_length %></h3>
			<h3>Description :<%= @movie[0].mv_desc %></h3>
                 </div>
	</div>
       <section id="clients" class="container clearfix">
		<h3>Showing On</h3>
		<hr />
                <% @movie.each do |row| %>
		<div class="col-md-2 col-sm-4 col-xs-12">
			<%= row.mv_name %>
                  
                        <%= image_tag(row.ch_image,:class => "img-responsive channel-image") %>
                        <%= row.timeslot.to_i*3 %>:00 hrs - <%= (row.timeslot.*3)+2 %>:00 hrs
		</div>
                <%end%>
	</section>	

  <% else %>
  
   <div class="search-error">
   <h1>No Results Found !</h1>
   </div>
  <%end%>

app/views/movies/show.html.erb
<!--################################################-->
	<div id="heroArea" class="clearfix">
            
		<div class="container">
                   <h1> <%= @movie[0].mv_name%> </h1>
                   <%= image_tag(@movie[0].mv_image,:class => "img-responsive movie-image") %>
		    


			<h3>Duration : <%= @movie[0].mv_length %></h3>
			<h3>Description :<%= @movie[0].mv_desc %></h3>
                 </div>
	</div>

        <section id="clients" class="container clearfix">
		<h3>Showing On</h3>
		<hr />
                <% @movie.each do |row| %>
		<div class="col-md-2 col-sm-4 col-xs-12">
			
                        <%= image_tag(row.ch_image,:class => "img-responsive channel-image") %>
                        <%= row.timeslot.to_i*3 %>:00 hrs - <%= (row.timeslot.to_i*3)+2 %>:00 hrs
		</div>
                <%end%>
	</section>	
	<!--################################################-->

app/views/slots/new.html.erb
<br/><br/><br/><br/><br/><br/><br/><br/>
<h1>Slots#new</h1>

<%= form_for @slot do |f| %>
  <% if @slot.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @slot.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <% @movie.each do |movie| %>
    
      <%= movie.id %>
      <%= movie.description %>
   <% end %>
  <% if !@movie.blank?%>
   <% for item in @movie %>
      <% item.description %> 
      <% item.id %>
     <% end %>
  <% end %>
<p>
  <% if !@channel.blank?%>
   <% for item in @channel %>
      <% item.name %> 
      <% item.id %>
     <% end %>
  <% end %>
</p>
  <p>
    
    <%= f.label :channel %><br />
    <%= f.text_field :channel_id %>
  </p>
  <p>
    <%= f.label :movie %><br />
    <%= f.text_field :movie_id %>
  </p>
  <p>
    <%= f.label :timeslot %><br />
    <%= f.text_field :timeslot %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/new.html.erb
<div class="container" style="margin-top:70px">
    <div class="row">
       <div class="col-sm-6 col-md-4 col-md-offset-4">
	   <div class="panel panel-default">
	       
                    <div class="row">
			<div class="center-block">
			   <img class="profile-img" src="/assets/register.jpg" alt="">
			</div>
		    </div>
                    <div class="row">
			<div class="col-sm-12 col-md-10  col-md-offset-1 ">
				    <%= form_for @user do |f| %>
					  <% if @user.errors.any? %>
					    <div class="error_messages">
					      <h2>Form is invalid</h2>
					      <ul>
						<% for message in @user.errors.full_messages %>
						  <li><%= message %></li>
						<% end %>
					      </ul>
					    </div>
				    <% end %>
				    <div class="form-group">
					<div class="input-group">
					     <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
					     <%= f.text_field :email,placeholder:"Enter Email"%>
				        </div>
				    </div>
				    <div class="form-group">
					<div class="input-group">
					     <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					     <%= f.password_field :password,placeholder:"Enter Password"%>
				        </div>
				    </div>
				    <div class="form-group">
					<div class="input-group">
					     <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
					     <%= f.password_field :password_confirmation,placeholder:"Confirm Password"%>
				        </div>
				    </div>
				  <p class="button"><%= f.submit "Register"%></p>
				<% end %>
                   </div>
	       </div>
           </div>
       </div>
    </div>
</div>